CREATE TABLE payment (
    id SERIAL PRIMARY KEY,
    boleto VARCHAR(255) UNIQUE NOT NULL,
    user_id VARCHAR(50) UNIQUE NOT NULL,
    payment_date VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL
);
